# This workflow runs API tests using Maven and TestNG and publishes the results.
name: API Test Automation

on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # Allows manual triggering from the GitHub UI
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run API Tests
        # The '-Dsuite=suite' should correspond to a valid test suite configuration in your pom.xml or a TestNG suite file.
        # The '-X' is for debug output, which can be useful but can be removed for cleaner logs.
        run: mvn clean test -Dsuite=suite -X

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: test-results
          path: |
            # These paths might vary, but this is a good practice to upload potential report locations.
            test-output/reports/
            target/surefire-reports/
            logs/

      - name: Publish Test Report
        if: always()
        uses: dorny/test-reporter@v1.8.0
        with:
          name: TestNG Results
          # Reverted path to point to the JUnit-style report generated by Maven
          path: target/surefire-reports/junitreports/TEST-*.xml
          # Reverted reporter type for JUnit
          reporter: java-junit
